rvm:
  - 1.8.7
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - rbx-18mode
  - rbx-19mode
gemfile:
  - test/gemfiles/Gemfile.rails-3.0.x
  - test/gemfiles/Gemfile.rails-3.1.x
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-master
matrix:
  exclude:
    # Don't kill Travis: just test against the latest version on Head, JRuby and rbx.
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-master }

    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }
    - { rvm: rbx-18mode, gemfile: test/gemfiles/Gemfile.rails-master }

    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.1.x }
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-master }

    - { rvm: ruby-head, gemfile: test/gemfiles/Gemfile.rails-3.0.x }
    - { rvm: ruby-head, gemfile: test/gemfiles/Gemfile.rails-3.1.x }
    - { rvm: ruby-head, gemfile: test/gemfiles/Gemfile.rails-master }

    - { rvm: 1.8.7, gemfile: test/gemfiles/Gemfile.rails-master }

  allow_failures:
    - { rvm: rbx-19mode, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: jruby-18mode, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: ruby-head, gemfile: test/gemfiles/Gemfile.rails-3.2.x }
    - { rvm: 1.9.3, gemfile: test/gemfiles/Gemfile.rails-master }

branches:
  only:
    - master
    - stable
    - 3-2-stable
    - 3-1-stable
script: "bundle exec rake submodules test"
